services:
  - type: web
    name: asistente-partnercomonicaa
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python asistente_partnerco.py
    envVars:
      - key: OPENAI_API_KEY
        sync: true
      - key: TELEGRAM_BOT_TOKEN
        sync: true
      - key: WEBHOOK_URL
        sync: true
    autoDeploy: true
